apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: snykmonitors.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: SnykMonitor
    listKind: SnykMonitorList
    plural: snykmonitors
    singular: snykmonitor
  scope: Namespaced
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            monitorSecrets:
              type: string
            image:
              properties:
                pullPolicy:
                  type: string
                repository:
                  type: string
                tag:
                  type: string
              type: object
            scope:
              type: string
            clusterName:
              type: string
            integrationApi:
              type: string
            temporaryStorageSize:
              type: string
  # "version" will be deprecated in apiextensions.k8s.io/v1
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
